name: Linux Build Job

on:
  workflow_call:
    inputs:
      targetFramework:
        type: string
        required: true
      configuration:
        type: string
        default: 'Debug'

jobs:
  build:
    name: build-linux-x64-${{ inputs.configuration }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Publish
        run: |
          dotnet publish Panzerfaust.csproj \
            --configuration ${{ inputs.configuration }} \
            --framework ${{ inputs.targetFramework }} \
            --runtime linux-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            --output Result.Linux.x64.${{ inputs.configuration }}/bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-linux-x64-${{ inputs.configuration }}
          path: Result.Linux.x64.${{ inputs.configuration }}/bin
          if-no-files-found: error
