name: Panzerfaust Linux Build

on:
  workflow_call:
    inputs:
      targetFramework:
        type: string
        required: true
      run_debug:
        type: boolean
        default: true
      run_release:
        type: boolean
        default: false
      run_deploy:
        type: boolean
        default: false

jobs:
  build-debug:
    if: ${{ inputs.run_debug }}
    uses: ./.github/workflows/job-build-linux.yml
    with:
      configuration: Debug
      targetFramework: ${{ inputs.targetFramework }}

  build-release:
    if: ${{ inputs.run_release || inputs.run_deploy }}
    uses: ./.github/workflows/job-build-linux.yml
    with:
      configuration: Release
      targetFramework: ${{ inputs.targetFramework }}

  deploy:
    needs: build-release
    if: ${{ inputs.run_deploy }}
    uses: ./.github/workflows/job-deploy-linux.yml
    with:
      configuration: Release
      targetFramework: ${{ inputs.targetFramework }}
