name: Panzerfaust macOS Build

on:
  workflow_call:
    inputs:
      targetFramework:
        type: string
        required: true
      run_debug:
        type: boolean
        default: true
      run_release:
        type: boolean
        default: false
      run_deploy:
        type: boolean
        default: false

jobs:
  build-debug:
    if: ${{ inputs.run_debug }}
    strategy:
      matrix:
        architecture: [x64, arm64]
    uses: ./.github/workflows/job-build-macOS.yml
    with:
      configuration: Debug
      architecture: ${{ matrix.architecture }}
      targetFramework: ${{ inputs.targetFramework }}

  build-release:
    if: ${{ inputs.run_release || inputs.run_deploy }}
    strategy:
      matrix:
        architecture: [x64, arm64]
    uses: ./.github/workflows/job-build-macOS.yml
    with:
      configuration: Release
      architecture: ${{ matrix.architecture }}
      targetFramework: ${{ inputs.targetFramework }}

  deploy:
    needs: build-release
    if: ${{ inputs.run_deploy }}
    strategy:
      matrix:
        architecture: [x64, arm64]
    uses: ./.github/workflows/job-deploy-macOS.yml
    with:
      configuration: Release
      architecture: ${{ matrix.architecture }}
      targetFramework: ${{ inputs.targetFramework }}
